version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - botnet
    deploy:
      restart_policy:
        condition: on-failure

  bot:
    image: adsr-jam-bot:latest
    environment:
      - PYTHONUNBUFFERED=1
      - API_TOKEN=${API_TOKEN}
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - botnet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mysql_data:

networks:
  botnet: